services:
  db:
    image: postgres:17 
    container_name: database
    environment:
      - POSTGRES_USER=batman  
      - POSTGRES_PASSWORD=robin1234
      - POSTGRES_DB=arkham_asylum
    ports:
      - 3000:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data  

    