

name: Deploy Batman

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Move files to the correct folder
      run: |
        mkdir -p public
        cp -r frontend/templates/* public/
        cp -r frontend/static public/static

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  
        folder: public
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

  
