name: Deploy Batman

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Build project
      run: echo "No build necessary"  

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  
        folder: ./frontend
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
        force: true
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}



  